# Generated by Django 3.2.12 on 2023-09-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsRules', '0001_firstMigration'),
    ]

    operations = [
    ]
